# Generated by Django 4.0.2 on 2022-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('altitude_accuracy', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'user_location',
            },
        ),
    ]
