# Generated by Django 4.0.2 on 2022-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='google_maps_location',
            field=models.TextField(null=True),
        ),
    ]
