# Generated by Django 4.0.2 on 2022-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userlocation_google_maps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('denied', 'Denied')], default='new', max_length=10),
        ),
    ]
